### ISSUE TITLE
webpack动态创建入口文章不详细？

### ISSUE THREAD

**Issue by luojinghui** [moyueating/FE-Garden#1]
1. getPlugin的函数的第一行`let = [...plugin]`是不是写错了，然后末尾没有导出函数？
2. `yarn start`之后，怎么访问多入口？

**Comment by moyueating** [comment]
@luojinghui 第一行只是偷懒了，代表数组里面你使用的其他插件，末尾的导出函数确实遗漏了，谢谢指正！ 没尝试使用过yarn

**Comment by moyueating** [comment]
@luojinghui 谢谢指出错误，疏忽遗漏了。yarn的话尝试的不多，你可以看看官方文档。

**Comment by luojinghui** [comment]
@moyueating 嗨，我想再问一下，多入口这个做法你有尝试过吗？可以使用吗？

**Comment by luojinghui** [comment]
我根据你这个做法运行起来后，命令行没有报错，但是页面加载的html貌似没有注入js，不知道是为什么？

**Comment by moyueating** [comment]
@luojinghui 嗯，当前项目正在使用的，可以在编辑器控制台打印一下debugger一下
